### ISSUE TITLE
ERROR ref_block_num: number is out of range, wrong type on abi json field ?

### ISSUE THREAD

**Issue by lucgerrits** [EOSIO/abieos#65]
Hi guys,
I've been testing this lib for a while.
I'm quite sure there is an issue with the file [transaction.abi.json](https://github.com/EOSIO/eosjs/blob/11fbd89d1fe78eb6807b89e1da38b4dc02bfb0f5/src/transaction.abi.json).
When the blockchain has more then 65535 blocks the abieos_json_to_bin_reorderable function fails with a number is out of range error (Iuse the same checks then the test file).

The problem is when the blockchain has more then 65535 blocks the json->bin is wrong. I've also made a script to compare the result with cleos.
Also if changing in  [transaction.abi.json](https://github.com/EOSIO/eosjs/blob/11fbd89d1fe78eb6807b89e1da38b4dc02bfb0f5/src/transaction.abi.json):
```
                {
                    "name": "ref_block_num",
                    "type": "uint16"
                },
```
to :
```
                {
                    "name": "ref_block_num",
                    "type": "uint32"
                },
```
it will remove the error but the result will be wrong and the bin->json is corrupted.

If you have a solution to correct the conversion corruption please let me know :) !

Thanks in advance.

**Comment by lucgerrits** [comment]
Update: As an [example of this issue](https://github.com/lucgerrits/EOS.IO-cpp-client/issues/1#issue-731277999), you can test is with [my program here](https://github.com/lucgerrits/EOS.IO-cpp-client).

**Comment by tbfleming** [comment]
`ref_block_num` expects the 16 LSBs of the block number

**Comment by lucgerrits** [comment]
Thanks a lot, it fixed my issue.
