### ISSUE TITLE
u0000 becomes \u0000 problem

### ISSUE THREAD

**Issue by gzliudan** [EOSIO/abieos#96]
Ihen I use cleos to get a block, the data of action in this block contains:
```
"qr_code": "u000001100001000320000001"
```
but after I decode it from binary data use function abieos_bin_to_json, it becomes "qr_code":"\u000001100001000320000001". This result add a char \ and make it contains a wrong unicode \u0000 .

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
